{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntest_fail.py:8: AssertionError"}, "start": 1747922926168, "stop": 1747922926168, "uuid": "1e4bc051-23c6-429f-b570-419a323ef4b9", "historyId": "3871665697ea3d8351c8bbb21a2393bd", "testCaseId": "3871665697ea3d8351c8bbb21a2393bd", "fullName": "tests.simple.test_fail#test_fail3", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}