{"name": "test_fail4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail4():\n>       assert False\nE       assert False\n\ntest_fail.py:11: AssertionError"}, "start": 1747924138489, "stop": 1747924138489, "uuid": "9269cda7-74c2-4353-8c7d-9a16d0aaf8de", "historyId": "f9f49e04500ac018e8389a41fc795dc7", "testCaseId": "f9f49e04500ac018e8389a41fc795dc7", "fullName": "tests.simple.test_fail#test_fail4", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "19780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}