{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntest_fail.py:8: AssertionError"}, "start": 1747922923517, "stop": 1747922923517, "uuid": "bba19327-a2b6-4923-a30f-3c78a43e585c", "historyId": "3871665697ea3d8351c8bbb21a2393bd", "testCaseId": "3871665697ea3d8351c8bbb21a2393bd", "fullName": "tests.simple.test_fail#test_fail3", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}