{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntest_fail.py:5: AssertionError"}, "start": 1747923427911, "stop": 1747923427911, "uuid": "ba1c80f6-dd87-4599-b3df-5b48500e69fe", "historyId": "c34ce9c1ddd89c5349df16e9084d0f7d", "testCaseId": "c34ce9c1ddd89c5349df16e9084d0f7d", "fullName": "tests.simple.test_fail#test_fail2", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "19184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}