{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntest_fail.py:5: AssertionError"}, "start": 1747922923513, "stop": 1747922923513, "uuid": "1d1146fa-608d-456c-860d-9bbb5a217a10", "historyId": "c34ce9c1ddd89c5349df16e9084d0f7d", "testCaseId": "c34ce9c1ddd89c5349df16e9084d0f7d", "fullName": "tests.simple.test_fail#test_fail2", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}