{"name": "test_fail4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail4():\n>       assert False\nE       assert False\n\ntest_fail.py:11: AssertionError"}, "start": 1747924468616, "stop": 1747924468616, "uuid": "4314a73e-576e-4936-903a-e739d3dcdb58", "historyId": "f9f49e04500ac018e8389a41fc795dc7", "testCaseId": "f9f49e04500ac018e8389a41fc795dc7", "fullName": "tests.simple.test_fail#test_fail4", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "20048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}