{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntest_fail.py:5: AssertionError"}, "start": 1747922926163, "stop": 1747922926163, "uuid": "f6e3b091-4454-4f58-98c6-374cf1fb56ce", "historyId": "c34ce9c1ddd89c5349df16e9084d0f7d", "testCaseId": "c34ce9c1ddd89c5349df16e9084d0f7d", "fullName": "tests.simple.test_fail#test_fail2", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}