{"name": "test_fail5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail5():\n>       assert False\nE       assert False\n\ntest_fail.py:14: AssertionError"}, "start": 1747922926177, "stop": 1747922926177, "uuid": "9fe49860-0f1e-4ea7-b916-8e4a6fc09fe7", "historyId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "testCaseId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "fullName": "tests.simple.test_fail#test_fail5", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}