{"name": "test_fail5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail5():\n>       assert False\nE       assert False\n\ntest_fail.py:14: AssertionError"}, "start": 1747923427923, "stop": 1747923427924, "uuid": "a9784ef1-723e-4134-9426-1d6801e182df", "historyId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "testCaseId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "fullName": "tests.simple.test_fail#test_fail5", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "19184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}